import * as anchor from '@coral-xyz/anchor';
import { Program, BN } from '@coral-xyz/anchor';
import { PublicKey, Keypair, SystemProgram } from '@solana/web3.js';
import {
	createAssociatedTokenAccountIdempotent,
	createMint,
	mintTo,
	getAccount,
	TOKEN_2022_PROGRAM_ID,
} from '@solana/spl-token';
import { assert } from 'chai';

// Generated by `anchor build`. The path is relative to the Anchor workspace.
import { CredbridgeEscrow } from '../target/types/credbridge_escrow';

describe('credbridge_escrow', () => {
	const provider = anchor.AnchorProvider.env();
	anchor.setProvider(provider);

	const program = anchor.workspace.CredbridgeEscrow as Program<CredbridgeEscrow>;
	const authority = (provider.wallet as anchor.Wallet).payer;
	const payer = Keypair.generate();
	const offrampOwner = Keypair.generate();

	let mint: PublicKey;
	let vendorId: number[];
	let vaultPda: PublicKey;
	let payerAta: PublicKey;
	let vaultAta: PublicKey;
	let offrampAta: PublicKey;

	const decimals = 6;
	const purposeCode = 'S1007';

	before(async () => {
		// Airdrop SOL to ephemeral keypairs.
		for (const kp of [payer, offrampOwner]) {
			const sig = await provider.connection.requestAirdrop(kp.publicKey, 2e9);
			await provider.connection.confirmTransaction(sig, 'confirmed');
		}

		mint = await createMint(
			provider.connection,
			authority,
			authority.publicKey,
			null,
			decimals,
			undefined,
			undefined,
			TOKEN_2022_PROGRAM_ID
		);

		vendorId = Array.from(Buffer.alloc(32, 7)); // deterministic fake vendor id

		[vaultPda] = PublicKey.findProgramAddressSync(
			[Buffer.from('vault'), Buffer.from(vendorId)],
			program.programId
		);

		vaultAta = await createAssociatedTokenAccountIdempotent(
			provider.connection,
			authority,
			mint,
			vaultPda,
			{},
			TOKEN_2022_PROGRAM_ID
		);

		payerAta = await createAssociatedTokenAccountIdempotent(
			provider.connection,
			authority,
			mint,
			payer.publicKey,
			{},
			TOKEN_2022_PROGRAM_ID
		);

		offrampAta = await createAssociatedTokenAccountIdempotent(
			provider.connection,
			authority,
			mint,
			offrampOwner.publicKey,
			{},
			TOKEN_2022_PROGRAM_ID
		);

		// Mint 1,000 USDC equivalents to payer.
		await mintTo(
			provider.connection,
			authority,
			mint,
			payerAta,
			authority,
			1_000n * 10n ** BigInt(decimals),
			[],
			undefined,
			TOKEN_2022_PROGRAM_ID
		);
	});

	it('initializes a vault for a vendor', async () => {
		await program.methods
			.initializeVault(vendorId, purposeCode)
			.accounts({
				vault: vaultPda,
				mint,
				authority: authority.publicKey,
				systemProgram: SystemProgram.programId,
			})
			.rpc();

		const vault = await program.account.escrowVault.fetch(vaultPda);
		assert.equal(vault.purposeCode, purposeCode);
		assert.deepEqual(Array.from(vault.vendorId), vendorId);
		assert.equal(vault.isActive, true);
		assert.equal(vault.amount.toString(), '0');
	});

	it('rejects deposit of zero amount', async () => {
		try {
			await program.methods
				.deposit(new BN(0))
				.accounts({
					vault: vaultPda,
					payer: payer.publicKey,
					payerToken: payerAta,
					vaultToken: vaultAta,
					mint,
					tokenProgram: TOKEN_2022_PROGRAM_ID,
				})
				.signers([payer])
				.rpc();
			assert.fail('expected ZeroAmount');
		} catch (err: any) {
			assert.match(err.toString(), /ZeroAmount/);
		}
	});

	it('deposits USDC into the vault', async () => {
		const amount = new BN(100 * 10 ** decimals);
		await program.methods
			.deposit(amount)
			.accounts({
				vault: vaultPda,
				payer: payer.publicKey,
				payerToken: payerAta,
				vaultToken: vaultAta,
				mint,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([payer])
			.rpc();

		const vault = await program.account.escrowVault.fetch(vaultPda);
		assert.equal(vault.amount.toString(), amount.toString());

		const vaultTokenAccount = await getAccount(
			provider.connection,
			vaultAta,
			'confirmed',
			TOKEN_2022_PROGRAM_ID
		);
		assert.equal(vaultTokenAccount.amount.toString(), amount.toString());
	});

	it('releases funds to the off-ramp ATA', async () => {
		const amount = new BN(40 * 10 ** decimals);
		await program.methods
			.releaseToOfframp(amount)
			.accounts({
				vault: vaultPda,
				authority: authority.publicKey,
				vaultToken: vaultAta,
				offrampToken: offrampAta,
				mint,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.rpc();

		const vault = await program.account.escrowVault.fetch(vaultPda);
		assert.equal(vault.amount.toString(), String(60 * 10 ** decimals));

		const offrampTokenAccount = await getAccount(
			provider.connection,
			offrampAta,
			'confirmed',
			TOKEN_2022_PROGRAM_ID
		);
		assert.equal(offrampTokenAccount.amount.toString(), amount.toString());
	});

	it('rejects release exceeding vault balance', async () => {
		try {
			await program.methods
				.releaseToOfframp(new BN(10_000 * 10 ** decimals))
				.accounts({
					vault: vaultPda,
					authority: authority.publicKey,
					vaultToken: vaultAta,
					offrampToken: offrampAta,
					mint,
					tokenProgram: TOKEN_2022_PROGRAM_ID,
				})
				.rpc();
			assert.fail('expected InsufficientFunds');
		} catch (err: any) {
			assert.match(err.toString(), /InsufficientFunds/);
		}
	});
});
